[package]
name = "unit3d-announce"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.0", default-features = false, features = ["http1", "tokio", "query", "macros"] }
chrono = { version = "0.4.22", default-features = false }
dashmap = { version = "5.4.0", default-features = false }
dotenvy = { version = "0.15.0", default-features = false }
memchr = { version = "2.4.0", default-features = false, features = ['std'] }
rand = { version = "0.8.5", default-features = false, features = ["alloc", "small_rng"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sqlx = { version = "0.6.0", default-features = false, features = ["runtime-tokio-rustls", "macros", "mysql", "chrono", "ipnetwork" ] }
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "signal"] }
