[package]
name = "unit3d-announce"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.0", features = ["headers", "query", "macros", "http2"] }
chrono = { version = "0.4.22", features = ["std"]}
dashmap = "5.4.0"
dotenvy = "0.15"
hashbrown = "0.13.1"
hex = "0.4.3"
indexmap = "1.9.1"
clokwerk = "0.3.5"
memchr = { version = "2.4.0", features = ['std'] }
rand = { version = "0.8.5", features = ["alloc"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7.1"
serde_path_to_error = "0.1.8"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "macros", "mysql", "chrono", "ipnetwork" ] }
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["full"] }
